version: 0.2  # Define the buildspec version

phases:
  install:
    runtime-versions:
      python: 3.9  # Specify the Python version for the build environment
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib  # Install required dependencies in the 'lib' directory

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib  # Navigate to the directory where dependencies are installed
      - zip -r9 ../deployment_package.zip .  # Create a zip file with dependencies
      - cd ..
      - zip -g deployment_package.zip lambda_function.py  # Add the Lambda function code to the zip file

  post_build:
    commands:
      - echo "Updating Lambda Function..."
      # Deploy the new Lambda function package
      - aws lambda update-function-code --function-name YOUR_LAMBDA_FUNCTION_NAME --zip-file fileb://deployment_package.zip
      - echo "Deployment completed successfully!"
